/**
 * Shapes of the replica artwork generated by `scripts/build-replica-art.mjs` into
 * `art.generated.ts` from Teenage Engineering's panel line drawing (decision D9).
 *
 * All lengths are millimetres with y pointing toward the player. Control art is local to the
 * control's actuator centre as TE drew it; `offset` is that drawn centre minus the centre in
 * `knowledge/opxy/controls.json`, so `centre + offset` places the art exactly as drawn.
 */

/** A point in millimetres. */
export interface ArtPoint {
	readonly x: number;
	readonly y: number;
}

/** A circle in millimetres. */
export interface ArtCircle extends ArtPoint {
	readonly r: number;
}

/** A rectangle with rounded corners, in millimetres. */
export interface ArtRect extends ArtPoint {
	readonly w: number;
	readonly h: number;
	/** Corner radius. */
	readonly r: number;
}

/** A plain rectangle, in millimetres. */
export interface ArtBox extends ArtPoint {
	readonly w: number;
	readonly h: number;
}

/** One piece of printed artwork: a legend, an icon or a number. */
export interface ArtPath {
	/** SVG path data in control-local millimetres (absolute commands). */
	readonly d: string;
	/** Printed on the keycap (moves with it) or on the tile around it (the "num" label). */
	readonly part: 'cap' | 'tile';
	/** Stroke width for stroked artwork; absent for fills (all of TE's legends are fills). */
	readonly stroke?: number;
	/** Fill rule when it is not the SVG default (nonzero). */
	readonly rule?: 'evenodd';
}

/** Everything drawn for one key. */
export interface KeyArt {
	readonly offset: ArtPoint;
	/** Legend artwork, keycap-local. Empty for the legend-less step keys. */
	readonly legend: readonly ArtPath[];
	/** True when TE prints nothing on the key (the 16 step keys). */
	readonly legendless: boolean;
	/** Keycap radius as drawn. */
	readonly capRadius: number;
	/** LED window (centre and radius, keycap-local), or null for keys without one. */
	readonly led: ArtCircle | null;
	/** The key's tile as drawn: its full pitch cell (the visible tile is inset by the gap). */
	readonly tile: ArtRect;
}

/** One endless encoder: a knurled knob with a coloured cap in a round dish. */
export interface EncoderArt {
	readonly offset: ArtPoint;
	readonly legendless: true;
	/** Radius of the recessed dish. */
	readonly dish: number;
	/** Radius of the knob's top face. */
	readonly top: number;
	/** Radius of the coloured cap. */
	readonly cap: number;
	readonly tile: ArtRect;
}

/** The analog volume pot. */
export interface VolumeArt {
	readonly offset: ArtPoint;
	/** Outer radius of the knurled knob. */
	readonly outer: number;
	/** Radius of its top face. */
	readonly top: number;
	/** The pointer dimple as drawn, knob-local. */
	readonly dimple: ArtCircle;
	/** Angle of the drawn dimple in degrees, clockwise from 12 o'clock. */
	readonly dimpleAngle: number;
	readonly tile: ArtRect;
}

/** The speaker grille. */
export interface GrilleArt {
	readonly offset: ArtPoint;
	readonly holeRadius: number;
	/** Median distance between neighbouring holes. */
	readonly pitch: number;
	/** Holes per row, top to bottom. */
	readonly rows: readonly number[];
	/** Hole centres, local to the speaker tile centre, row by row. */
	readonly holes: readonly (readonly [number, number])[];
	readonly tile: ArtRect;
}

/** The display tile. */
export interface ScreenArt {
	readonly offset: ArtPoint;
	readonly tile: ArtRect;
}

/** A feature drawn against a body edge (the power switch tab, the pitch-bend pill). */
export interface EdgeFeature {
	/** Closed outline in panel millimetres. */
	readonly d: string;
	/** Which edge of the top face it sits beyond. */
	readonly edge: 'right' | 'bottom';
	readonly box: ArtBox;
}

/** Body-margin features, in panel millimetres. */
export interface PanelArt {
	readonly body: { readonly w: number; readonly h: number; readonly r: number };
	readonly mic: ArtCircle;
	/** The level meter's LED column (a vertical line in TE's drawing). */
	readonly meter: { readonly x: number; readonly y1: number; readonly y2: number };
	/** The white tick on the front margin. */
	readonly tick: ArtBox;
	readonly powerSwitch: EdgeFeature;
	readonly pitchBend: EdgeFeature;
}

/** Line-art extras for a TE-guide style theme, in panel millimetres. */
export interface GuideArt {
	/** The small star-shaped marks where tile corners meet. */
	readonly junctions: string;
	/** The grid's outer frame. */
	readonly frame: string;
}

/** A drawing path that was removed or ignored, with why. */
export interface ArtExclusion {
	readonly index: number;
	readonly reason: string;
}

/** Provenance, transform, residual and coverage of the generated art. */
export interface ArtSource {
	readonly file: string;
	readonly asset: string;
	readonly sha256: string;
	readonly viewBox: readonly number[];
	/** Paths in the drawing, exact duplicates dropped, and subpaths left. */
	readonly paths: number;
	readonly duplicates: number;
	readonly subpaths: number;
	/** Drawing units → millimetres: `mm = a·u + b` per axis, `[a, b]`. */
	readonly transform: {
		readonly x: readonly [number, number];
		readonly y: readonly [number, number];
		readonly basis: string;
	};
	/** The same, fixed by the body outline alone. */
	readonly bodyTransform: {
		readonly x: readonly [number, number];
		readonly y: readonly [number, number];
		readonly basis: string;
	};
	/**
	 * Distance between controls.json centres and the drawn features under the fitted transform
	 * (rms, max), and the mean offset under the body transform.
	 */
	readonly residual: {
		readonly rms: number;
		readonly max: number;
		readonly maxId: string;
		readonly bodyRms: number;
		readonly bodyOffset: readonly [number, number];
	};
	readonly measured: {
		readonly keycapDiameter: number;
		readonly ledDiameter: number;
		readonly ledOffset: readonly [number, number];
		readonly tileCornerRadius: number;
		readonly bodyCornerRadius: number;
		readonly grilleHoles: number;
	};
	readonly coverage: {
		/** Paths per category (body, tile, keycap, led, legend, junction, logo, …). */
		readonly assigned: Readonly<Record<string, number>>;
		/** Keys with printed legends. */
		readonly legendKeys: number;
		/** Controls TE prints nothing on (step keys and encoders). */
		readonly legendless: readonly string[];
		/** Wordmark paths removed (decision D6), with their panel-millimetre bounds. */
		readonly stripped: readonly (ArtExclusion & { readonly box: ArtBox })[];
		/** Drawing artefacts dropped. */
		readonly artifacts: readonly ArtExclusion[];
		/** Paths no rule could place (should stay empty). */
		readonly unassigned: readonly ArtExclusion[];
	};
}
