"""Writes the organ engine's registrations (src/lib/sound/synth/engines/organ-registrations.ts) from
organ_fit.py's measurements (<capture folder>/organ-fit.json).

Per type it keeps the partials that matter (within PRUNE_DB of the loudest of some take), snaps
ratios that sit on the half-note grid onto it, fills levels a take could not resolve from the
nearest note that did, and folds type 1's two moving partials (the bass knob slides them from the
8′ and 5⅓′ up to the 5⅓′ and 4′) into two partials that glide with bass. Levels are dBFS on the
device's USB audio, before the engine's high-pass, rounded to 0.5 dB.

Usage: uv run --with numpy python research/device/organ_emit.py <capture folder>
"""

import json
import math
import pathlib
import sys

import numpy as np

OUT = pathlib.Path(__file__).resolve().parents[2] / "src/lib/sound/synth/engines/organ-registrations.ts"
PRUNE_DB = 50  # partials never within this of their take's loudest are left out
ABSENT_DB = -120  # a partial not there at all
GRID = 3e-4  # ratios this close (relative) to a multiple of ½ are that multiple


def snap(r: float) -> float:
    k = round(r * 2)
    return k / 2 if k and abs(r * 2 - k) <= GRID * r * 2 else r


def fill(level: np.ndarray) -> np.ndarray:
    """Level [bass, note, partial] with NaN where a take could not resolve the partial: filled from
    the nearest note at the same bass that did (the higher on a tie: higher notes resolve better)."""
    out = level.copy()
    nb, nn, nk = level.shape
    for b in range(nb):
        for k in range(nk):
            known = [n for n in range(nn) if not math.isnan(level[b, n, k])]
            for n in range(nn):
                if math.isnan(level[b, n, k]):
                    out[b, n, k] = level[b, min(known, key=lambda m: (abs(m - n), -m)), k] if known else ABSENT_DB
    return out


def main() -> None:
    folder = pathlib.Path(sys.argv[1])
    fit = json.loads((folder / "organ-fit.json").read_text())
    types = []
    for t, ty in enumerate(fit["types"]):
        ratios = [snap(r) for r in ty["ratios"]]
        level = np.array([[[math.nan if v is None else v for v in row] for row in b] for b in ty["level_db"]])
        level = fill(level)
        partials = []  # (ratio, glide, level [bass, note])
        if t == 1:
            # the 16′ holds; two partials slide with bass: 8′ → 5⅓′ and 5⅓′ → 4′ (1.252 and 1.752 at 64)
            at = lambda r: min(range(len(ratios)), key=lambda k: abs(ratios[k] - r))  # noqa: E731
            partials.append((0.5, 0.0, level[:, :, at(0.5)]))
            for start in (1.0, 1.5):
                path = [at(start), at(start + 0.252), at(start + 0.5)]
                lv = np.stack([level[b, :, path[b]] for b in range(3)])
                partials.append((start, 0.5, lv))
        else:
            for k, r in enumerate(ratios):
                partials.append((r, 0.0, level[:, :, k]))
        loudest = np.max(np.stack([lv for _, _, lv in partials]), axis=0)  # [bass, note]
        kept = [(r, g, lv) for r, g, lv in partials if np.any(lv >= loudest - PRUNE_DB)]
        kept.sort(key=lambda p: p[0])
        types.append(kept)
        print(f"type {t}: {len(kept)} of {len(partials)} partials")

    lines = [
        "/**",
        " * The organ's registrations as measured on the owner's OP-XY (OS 1.1.33, 2026-09-27; filter,",
        " * LFO and FX off, a flat envelope): per type, every partial's ratio to the note and its level at",
        " * bass 0, 64 and 127 on the notes A1–A5. Generated by `research/device/organ_emit.py` from",
        " * `organ_fit.py`'s fit of an `organ` capture (`docs/research/57-synth-engines.md`, organ); do not",
        " * edit by hand.",
        " */",
        "",
        "/** The engine's output high-pass, one pole (Hz): the device's lowest partials fall off below it. */",
        f"export const ORGAN_HIGHPASS_HZ = {fit['highpass_hz']:.1f};",
        "/** The bass settings (0–1) and notes (MIDI) the levels were measured at. */",
        "export const ORGAN_BASS_POINTS = [0, 64 / 127, 1] as const;",
        f"export const ORGAN_NOTE_POINTS = {json.dumps(fit['notes'])} as const;",
        "",
        "/**",
        " * One partial: `ratio` to the note, plus `glide` × bass (0–1); `db`, its level in dBFS before the",
        " * high-pass, at each bass point (rows) and note point (columns), flattened.",
        " */",
        "export interface OrganPartial {",
        "\treadonly ratio: number;",
        "\treadonly glide: number;",
        "\treadonly db: readonly number[];",
        "}",
        "",
        "/** The eight types, in the order of the type knob. */",
        "export const ORGAN_REGISTRATIONS: readonly (readonly OrganPartial[])[] = [",
    ]
    for t, kept in enumerate(types):
        lines.append(f"\t// type {t + 1}")
        lines.append("\t[")
        for r, g, lv in kept:
            db = ", ".join(f"{round(v * 2) / 2:g}" for v in np.maximum(lv, ABSENT_DB).flatten())
            ratio = f"{r:g}" if r == snap(r) and (r * 2).is_integer() else f"{r:.5f}"
            lines.append(f"\t\t{{ ratio: {ratio}, glide: {g:g}, db: [{db}] }},")
        lines.append("\t],")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
